# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      frontendTag:
        description: "Test"
        required: false
        default: 'stable'
      backendTag:
        description: "Test"
        required: false
        default: 'develop'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
       frontend_tag: ${{ steps.generate_tag.outputs.frontend_tag }}
       backend_tag: ${{ steps.generate_tag.outputs.backend_tag }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Generate Application Tag
        id: generate_tag
        run: |
          # Frontend
          if [ -z ${{ github.event.inputs.frontendTag }} ]; then
             echo "frontend_tag=notstable" >> "$GITHUB_OUTPUT"
          else
             echo "frontend_tag=${{ github.event.inputs.frontendTag }}" >> "$GITHUB_OUTPUT"
          fi
          # Backend
          if [ -z ${{ github.event.inputs.backendTag }} ]; then
             echo "backend_tag=notdevelop" >> "$GITHUB_OUTPUT"
          else
             echo "backend_tag=${{ github.event.inputs.backendTag }}" >> "$GITHUB_OUTPUT"
          fi

      - name: echo env
        run: |
          echo ${{ steps.generate_tag.outputs.frontend_tag }}
          echo ${{ steps.generate_tag.outputs.backend_tag }}
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          path: test-repo

      # Runs a set of commands using the runners shell

      - name: create file
        id: create-file
        run: |
          touch testfile
          echo "testtest" > testfile
          #cp testfile /home/runner/work/test-repo/test-repo/
          #cat /home/runner/work/_temp/_github_home
      
      - name: Run a multi-line script
        uses: docker://ubuntu:latest
        with:
          args: cat /github/workspace/testfile

      - name: push tag
        run: |
          # checkout時のPATのrepoのFullコントロールで許可する
          # checkoutに必要
          cd test-repo
          ls -l
          git branch
          # git fetch origin develop
          # tag付けに必要
          # git checkout -b develop tags/test-20230831_044839
          git tag test-$(date +%Y%m%d_%H%M%S) develop
          git push origin test-$(date +%Y%m%d_%H%M%S)

      - name: cheout remote tag
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: apc-jnytnai0613/oidc-test
          path: oidc-test

      - name: push remote tag
        run: |
          cd oidc-test
          # checkout時のPATのrepoのFullコントロールで許可する
          # checkoutに必要
          # git fetch origin develop
          # tag付けに必要
          git checkout develop
          git tag test-$(date +%Y%m%d_%H%M%S) develop
          git push origin test-$(date +%Y%m%d_%H%M%S)

      - name: pwd1
        run: |
          export TEST=taniai
          cd test-repo
          pwd

      - name: pwd2
        run: |
          echo $TEST
          pwd

  # This workflow contains a single job called "build"
  echo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: echo env
        run: |
          echo ${{ needs.build.outputs.frontend_tag }}
          echo ${{ needs.build.outputs.backend_tag }}
