# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: touch /home/runner/work/test-repo/test-repo/test
      - name: test1
        uses: docker://amazon/aws-cli:2.13.12
        with:
          args: --version > test
      - name: view file
        run: |
          ls -l
          cat /home/runner/work/test-repo/test-repo/test
